#!/bin/bash

set -euo pipefail

GO_VERSION=1.13.3
KUBECTL_VERSION=v1.16.0

if [ "$(uname)" == "Linux" ]; then
    sudo apt-get update && \
        sudo apt-get install -y software-properties-common \
            ca-certificates \
            curl \
            apt-transport-https \
            lsb-release \
            gnupg \
            build-essential \
            curl \
            git-core \
            jq \
            python-dev \
            python-pip \
            python3-dev \
            python3-pip \
            silversearcher-ag \
            tmux \
            nodejs \
            yarn \
            highlight \
            zsh

    if [ ! -f "/etc/apt/sources.list.d/kubernetes.list" ]; then
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
    fi

    if [ ! -f "/etc/apt/trusted.gpg.d/microsoft.asc.gpg" ]; then
        curl -sL https://packages.microsoft.com/keys/microsoft.asc | 
            gpg --dearmor | 
            sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null
    fi

    if [ ! -f "/etc/apt/sources.list.d/azure-cli.list" ]; then
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | 
            sudo tee /etc/apt/sources.list.d/azure-cli.list
    fi

        sudo apt-get update && \
        sudo apt-get install -y \
            kubectl \
            azure-cli
fi

if [ "$(uname)" == "Darwin" ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew bundle install
fi

# Installed via Brewfile on Mac
if [ "$(uname)" == "Linux" ]; then
    mkdir -p $HOME/bin
    mkdir -p $HOME/.kube
    mkdir -p $HOME/Code

    # install go
    curl -L https://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz | sudo tar -C /usr/local -xz

    if [ ! -d "$HOME/Code/github.com/jonmosco" ]; then
        mkdir -p $HOME/Code/github.com/jonmosco
        git clone https://github.com/jonmosco/kube-ps1.git $HOME/Code/github.com/jonmosco/kube-ps1
    fi

    if [ ! -d "$HOME/Code/github.com/ahmetb" ]; then
        mkdir -p $HOME/Code/github.com/ahmetb
        git clone https://github.com/ahmetb/kubectx.git $HOME/Code/github.com/ahmetb/kubectx
    fi
fi

# neovim python extensions
pip install pynvim --upgrade --disable-pip-version-check --no-cache-dir && pip3 install pynvim --upgrade --disable-pip-version-check --no-cache-dir

# pygmentize
# pip3 install --upgrade --disable-pip-version-check --no-cache-dir pygmentize

# Oh my zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash
    sudo usermod -s /bin/zsh "${USER}"
    rm "$HOME/.zshrc"
fi

# base16 shell themes
if [ ! -d "$HOME/.config/base16-shell" ]; then
    git clone https://github.com/chriskempson/base16-shell.git "$HOME/.config/base16-shell" #&& \
        # ln -s "$HOME/.config/base16-shell/scripts/base16_tomorrow-night.sh" "$HOME/.base16_theme"
fi

# fzf
if [ ! -d "$HOME/.fzf" ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git "$HOME/.fzf" && "$HOME/.fzf/install" --no-update-rc
fi

zsh -c make all

# vim: ts=4 sw=4 et
