#!/bin/bash

set -euo pipefail

apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:neovim-ppa/stable && \
    apt-get update &&\
    apt-get install -y \
        build-essential \
        curl \
        git-core \
        jq \
        language-pack-en \
        neovim \
        python-dev \
        python-pip \
        python3-dev \
        python3-pip \
        silversearcher-ag \
        tmux \
        zsh

# neovim python extensions
pip install neovim --upgrade && pip3 install neovim --upgrade

# Oh my zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash
    chsh -s /bin/zsh
    rm "$HOME/.zshrc"
fi

# base16 shell themes
if [ ! -d "$HOME/.config/base16-shell" ]; then
    git clone https://github.com/chriskempson/base16-shell.git "$HOME/.config/base16-shell" #&& \
        # ln -s "$HOME/.config/base16-shell/scripts/base16_tomorrow-night.sh" "$HOME/.base16_theme"
fi

# fzf
if [ ! -d "$HOME/.fzf" ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git "$HOME/.fzf" && "$HOME/.fzf/install" --no-update-rc
fi

zsh -c make all

# vim: ts=4 sw=4 et
