FROM ubuntu:17.10

ENV HOME=/root \
         LC_ALL=en_US.UTF-8 \
         LANG=en_US.UTF-8 \
         LANGUAGE=en_US.UTF-8

RUN apt-get update && \
        apt-get install -y software-properties-common && \
        add-apt-repository ppa:neovim-ppa/stable && \
        apt-get update &&\
        apt-get install -y \
            build-essential \
            curl \
            git-core \
            jq \
            language-pack-en \
            neovim \
            python-dev \
            python-pip \
            python3-dev \
            python3-pip \
            silversearcher-ag \
            tmux \
            zsh && \
        rm -rf /var/lib/apt/lists/* && \
        locale-gen en_US.UTF-8

# neovim python extensions
RUN pip install neovim --upgrade && \
        pip3 install neovim --upgrade

# Oh my zsh
RUN curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash
RUN chsh -s /bin/zsh

# tmux plugin manager
COPY tmux.conf $HOME/.tmux.conf
RUN git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm && \
        $HOME/.tmux/plugins/tpm/bin/install_plugins

# base16 shell themes
RUN git clone https://github.com/chriskempson/base16-shell.git $HOME/.config/base16-shell && \
        ln -s $HOME/.config/base16-shell/scripts/base16_classic-dark.sh $HOME/.base16_theme

# fzf
RUN git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf && \
        $HOME/.fzf/install

COPY aliases $HOME/.aliases
COPY exports $HOME/.exports
COPY functions $HOME/.functions
COPY path $HOME/.path
COPY vimrc $HOME/.vimrc
COPY zsh_profile $HOME/.zsh_profile
COPY zshrc $HOME/.zshrc
COPY init.vim $HOME/.config/nvim/init.vim

RUN nvim +PlugInstall +UpdateRemotePlugins +qall

WORKDIR $HOME

CMD /bin/zsh
