#!/bin/bash

sudo apt install -y \
  software-properties-common \
  tmux \
  python \
  python-pip \
  python3 \
  python3-pip \
  highlight \
  silversearcher-ag \
  httpie \

sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt update
sudo apt install -y neovim

pip install neovim
pip3 install neovim

if [ ! -d ~/go ]; then
  curl -L https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz | sudo tar -C /usr/local -xz
fi

if [ ! -f /usr/local/bin/kubectl ]; then
  sudo curl -sSL https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
  sudo chmod +x /usr/local/bin/kubectl
fi

if [ ! -d ~/go ]; then
  mkdir ~/go
fi

if [ ! -d ~/bin ]; then
  mkdir ~/bin
fi

if [ ! -d ~/.oh-my-zsh ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

if [ ! -f ~/.vim/autoload/plug.vim ]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ ! -f ~/.local/share/nvim/site/autoload/plug.vim ]; then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

[ ! -d ~/.config ] && mkdir ~/.config
[ ! -d ~/.config/nvim ] && mkdir ~/.config/nvim

